import { Hono } from "hono";
import type { HonoEnv } from "../types";
import { badRequest, tooMany } from "../lib/errors";
import { checkRateLimit } from "../lib/rate-limit";
import { writeAppEvent, type AppEventType } from "../lib/analytics";

export const appRoutes = new Hono<HonoEnv>();

// UUIDv4 regex (case-insensitive) — matches the shape generated by crypto.randomUUID().
const UUID_V4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const PLATFORMS = new Set(["desktop", "android"]);
const MAX_VERSION_LEN = 32;
const MAX_OS_LEN = 16;

interface AppEventBody {
  installId?: unknown;
  appVersion?: unknown;
  platform?: unknown;
  os?: unknown;
}

// Validates incoming payload shape. Returns the cleaned values or throws.
// Never logs the payload — the installId is treated as sensitive.
function parseBody(body: AppEventBody) {
  const installId = typeof body.installId === "string" ? body.installId : "";
  const appVersion = typeof body.appVersion === "string" ? body.appVersion : "";
  const platform = typeof body.platform === "string" ? body.platform : "";
  const os = typeof body.os === "string" ? body.os : "";
  if (!UUID_V4.test(installId)) throw badRequest("invalid request");
  if (!appVersion || appVersion.length > MAX_VERSION_LEN) throw badRequest("invalid request");
  if (!PLATFORMS.has(platform)) throw badRequest("invalid request");
  if (os.length > MAX_OS_LEN) throw badRequest("invalid request");
  return { installId, appVersion, platform: platform as "desktop" | "android", os };
}

// Uses the CF edge's visitor-ip header for rate-limit keying. The Cache API backing
// checkRateLimit is per-colo, which is fine for casual abuse prevention.
function clientIp(c: any): string {
  return c.req.header("CF-Connecting-IP") || c.req.header("X-Forwarded-For") || "unknown";
}

async function handleEvent(c: any, eventType: AppEventType, rateKey: string, limit: number) {
  const ip = clientIp(c);
  if (!(await checkRateLimit(`${rateKey}:${ip}`, limit, 3600))) {
    throw tooMany("too many requests");
  }
  const body = (await c.req.json().catch(() => ({}))) as AppEventBody;
  const parsed = parseBody(body);
  const country = c.req.header("CF-IPCountry") || "";
  writeAppEvent(c.env, { eventType, ...parsed, country });
  return c.json({ ok: true });
}

// POST /app/install — fired once per install (first-launch).
// Rate-limited at 10/hour/IP: legit users hit it exactly once; higher is abuse.
appRoutes.post("/app/install", (c) => handleEvent(c, "install", "app-install", 10));

// POST /app/heartbeat — fired at most once/day per install.
// Rate-limited at 30/hour/IP: generous for dev-machine bouncing between builds.
appRoutes.post("/app/heartbeat", (c) => handleEvent(c, "heartbeat", "app-heartbeat", 30));
